DIRS = \
  Client7z\~ \
  Console\~ \
  Explorer\~ \
  Far\~ \
  FileManager\~ \
  GUI\~ \

DIRS = \
  Console\~ \
  Explorer\~ \
  FileManager\~ \
  GUI\~ \

all: $(DIRS)

$(DIRS):
!include "../SubBuild.mak"
